# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms" 

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(380, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 120, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 230, 81, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 71, 16))
        self.label_5.setObjectName("label_5")
        self.txtplaintext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtplaintext.setGeometry(QtCore.QRect(90, 90, 251, 71))
        self.txtplaintext.setObjectName("txtplaintext")
        self.txtinfo = QtWidgets.QTextEdit(self.centralwidget)
        self.txtinfo.setGeometry(QtCore.QRect(530, 90, 251, 71))
        self.txtinfo.setObjectName("txtinfo")
        self.txtsign = QtWidgets.QTextEdit(self.centralwidget)
        self.txtsign.setGeometry(QtCore.QRect(530, 210, 251, 71))
        self.txtsign.setObjectName("txtsign")
        self.txtciphertext = QtWidgets.QTextEdit(self.centralwidget)
        self.txtciphertext.setGeometry(QtCore.QRect(90, 210, 251, 71))
        self.txtciphertext.setObjectName("txtciphertext")
        self.btnencrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btnencrypt.setGeometry(QtCore.QRect(30, 360, 101, 23))
        self.btnencrypt.setObjectName("btnencrypt")
        self.btnverify = QtWidgets.QPushButton(self.centralwidget)
        self.btnverify.setGeometry(QtCore.QRect(580, 360, 101, 23))
        self.btnverify.setObjectName("btnverify")
        self.btnsign = QtWidgets.QPushButton(self.centralwidget)
        self.btnsign.setGeometry(QtCore.QRect(390, 360, 101, 23))
        self.btnsign.setObjectName("btnsign")
        self.btdecrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btdecrypt.setGeometry(QtCore.QRect(200, 360, 101, 23))
        self.btdecrypt.setObjectName("btdecrypt")
        self.btngenkey = QtWidgets.QPushButton(self.centralwidget)
        self.btngenkey.setGeometry(QtCore.QRect(550, 30, 101, 23))
        self.btngenkey.setObjectName("btngenkey")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "PLAIN TEXT"))
        self.label_3.setText(_translate("MainWindow", "INFORMATION"))
        self.label_4.setText(_translate("MainWindow", "SIGNUTARE"))
        self.label_5.setText(_translate("MainWindow", "CIPHER TEXT"))
        self.btnencrypt.setText(_translate("MainWindow", "ENCYPT"))
        self.btnverify.setText(_translate("MainWindow", "VERIFY"))
        self.btnsign.setText(_translate("MainWindow", "SIGN"))
        self.btdecrypt.setText(_translate("MainWindow", "DECYPT"))
        self.btngenkey.setText(_translate("MainWindow", "GENKEY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
